// ============================================================
// Condor — Report ingestion endpoint (future Enki feed)
//
// POST /api/ingest   Authorization: Bearer <ENKI_API_TOKEN>
//
// This is the forward-looking entry point for the planned "Enki"
// AI data feed. Today, reports are generated by the weekly GitHub
// Action (scripts/generate.js → Perplexity → Supabase). When Enki
// comes online it will POST reports here instead, using the same
// report_json schema, so nothing downstream (dashboard, chat AI,
// scoring) has to change.
//
// Env:
//   ENKI_API_TOKEN       — shared secret; endpoint is disabled until set
//   SUPABASE_URL / SUPABASE_SERVICE_KEY
// ============================================================

import { db } from '../lib/condor-data.js';

const REQUIRED_FIELDS = ['location_code', 'location_name', 'country', 'report_date'];

export default async function handler(req, res) {
  res.setHeader('Cache-Control', 'no-store');
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const token = process.env.ENKI_API_TOKEN;
  if (!token) {
    res.status(503).json({ error: 'Ingestion endpoint is not enabled (ENKI_API_TOKEN not configured).' });
    return;
  }
  const auth = req.headers.authorization || '';
  if (auth !== `Bearer ${token}`) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }

  try {
    const body = typeof req.body === 'string' ? JSON.parse(req.body) : (req.body || {});
    const reports = Array.isArray(body.reports) ? body.reports : [body];

    const errors = [];
    reports.forEach((r, i) => {
      for (const f of REQUIRED_FIELDS) {
        if (!r || typeof r[f] !== 'string' || !r[f].trim()) errors.push(`reports[${i}].${f} is required`);
      }
    });
    if (errors.length) {
      res.status(400).json({ error: 'Validation failed', details: errors.slice(0, 20) });
      return;
    }

    const rows = reports.map(r => ({
      location_code: r.location_code.toUpperCase(),
      location_name: r.location_name,
      city: r.city || null,
      facility_type: r.facility_type || null,
      country: r.country,
      report_date: r.report_date,
      week_label: r.week_label || `Week of ${r.report_date}`,
      report_json: r,
      sources_cited: r.sources_cited || [],
      data_gaps: r.data_gaps || [],
      created_at: new Date().toISOString(),
    }));

    const { error } = await db().from('reports').insert(rows);
    if (error) throw error;

    res.status(201).json({ inserted: rows.length });
  } catch (err) {
    console.error('ingest error:', err);
    res.status(500).json({ error: 'Ingestion failed' });
  }
}
